{
 "title": "RabbitMQ Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "RabbitMQ Server status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_up" }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_running", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Disk limit Alarm",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_node_disk_free_alarm)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory limit Alarm",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rabbitmq_node_mem_alarm)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Messages in queue",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rabbitmq_queue_messages", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Messages/host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_ready)",
     "legendFormat": "{{vhost}}:ready"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_published_total)",
     "legendFormat": "{{vhost}}:published"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_delivered_total)",
     "legendFormat": "{{vhost}}:delivered"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_unacknowledged)",
     "legendFormat": "{{vhost}}:unack"
    }
   ]
  },
  {
   "title": "Messages / Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages", "legendFormat": "{{queue}}:{{durable}}" }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queues", "legendFormat": "{{instance}}:queues" }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_channels", "legendFormat": "{{instance}}:channels" }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_consumers", "legendFormat": "{{instance}}:consumers" }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_connections", "legendFormat": "{{instance}}:connections" }
   ]
  },
  {
   "title": "Exchanges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_exchanges", "legendFormat": "{{instance}}:exchanges" }
   ]
  },
  {
   "title": "FIle descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_fd_used", "legendFormat": "{{node}}:used" },
    { "expr": "rabbitmq_fd_total", "legendFormat": "{{node}}:total" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "rabbitmq_node_mem_used", "legendFormat": "{{node}}:used" },
    { "expr": "rabbitmq_node_mem_limit", "legendFormat": "{{node}}:limit" }
   ]
  },
  {
   "title": "Sockets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_sockets_used", "legendFormat": "{{node}}:used" },
    { "expr": "rabbitmq_sockets_total", "legendFormat": "{{node}}:total" }
   ]
  }
 ]
}