apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: http://172.20.240.3:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
    basicAuth: false
    isDefault: true
    editable: true